[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale = "2uZ2ZJB4wLwxfqJCQjB2rCmtZoMcRbTMcHkcQrgabVur"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
